#!/bin/bash

# config
SOURCE_URL=''
FOLDER_NAME="temp"

#welcome
echo "-------------------"
echo "ORBS LIGHT MY PATH!"
echo "-------------------"

#check param 1
if [ -z "$1" ]
then
    echo ""
    echo "Usage:"
    echo "./invoker SOURCE FOLDER"
    echo ""
    echo "Source:"
    echo "Supply URL to download (copy and paste from Bandcamp download link)"
    echo ""
    echo "Folder:"
    echo "The folder name to store everything locally"
    echo ""
    exit 1
else
    SOURCE_URL="$1"
    echo "Source file set!"
fi

#check param 2
if [ -z "$2" ]
then
    echo "Download folder name ommitted, using temp as folder name"
else
    FOLDER_NAME="$2"
    echo "Download folder set to: '$2'"
fi

#invoke
echo "Downloading from bandcamp..."
echo "----"
wget $SOURCE_URL -O 'temp.zip'
echo "----"
echo "Download complete, unzipping..."
unzip 'temp.zip' -d "$FOLDER_NAME"
echo "----"
echo "Unzip complete, removing temp zip file..."
rm -f 'temp.zip'
echo "--------------------"
echo "Glorious invocation!"
